### ISSUE TITLE
CSS not correct for enlarging the image on click

### ISSUE THREAD

**Issue by d3chapma** [toddjordan/ember-cli-tutorial-style#2]
I'm going through the Ember tutorial and my images are barely enlarging when I click them. Looks to me like the following rule in css:

```
.listing a.image {
    max-width: 150px;
    display: block;
}
```

should be:

```
.listing a.image:not(.wide) {
    max-width: 150px;
    display: block;
}
```

**Comment by toddjordan** [comment]
Thanks for reporting.  I'll take a look this week

**Comment by toddjordan** [comment]
Tried on chrome, firefox, safari, and brave... seems to be working.  What browser are you seeing this on?  is your markup different than the tutorial?

![image](https://cloud.githubusercontent.com/assets/3609063/16892933/f4fb7772-4af2-11e6-8c02-1071ee78f0a7.png)

**Comment by omarkohl** [comment]
I get the same issue on Firefox 47 and Chromium 51.

```css
.listing .wide {
  max-width: 100%;
  position: relative;
  z-index: 999;
}

.listing a.image {
  max-width: 150px;
  display: block;
}
```

The second selector is more specific and therefore wins (overriding max-width).

Apart from the previously mentioned fix this also works (making the first selector more specific):

```css
.listing a.image.wide {
  max-width: 100%;
  position: relative;
  z-index: 999;
}

.listing a.image {
  max-width: 150px;
  display: block;
}
```
